// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Achievements/Achievements.tsx";
import * as $$$$$$1 from "./sections/Benefits/Benefits.tsx";
import * as $$$$$$2 from "./sections/Gallery.tsx";
import * as $$$$$$3 from "./sections/Hero/Hero.tsx";
import * as $$$$$$4 from "./sections/Images/Carousel.tsx";
import * as $$$$$$5 from "./sections/Problem/Problem.tsx";
import * as $$$$$$6 from "./sections/Theme/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/deco-camp/loaders/List/Sections.tsx": $$$0,
  },
  "sections": {
    "deco-sites/deco-camp/sections/Achievements/Achievements.tsx": $$$$$$0,
    "deco-sites/deco-camp/sections/Benefits/Benefits.tsx": $$$$$$1,
    "deco-sites/deco-camp/sections/Gallery.tsx": $$$$$$2,
    "deco-sites/deco-camp/sections/Hero/Hero.tsx": $$$$$$3,
    "deco-sites/deco-camp/sections/Images/Carousel.tsx": $$$$$$4,
    "deco-sites/deco-camp/sections/Problem/Problem.tsx": $$$$$$5,
    "deco-sites/deco-camp/sections/Theme/Theme.tsx": $$$$$$6,
  },
  "apps": {
    "deco-sites/deco-camp/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/deco-camp/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/deco-camp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
